export const FIELD_LABELS: Record<string, Record<string, string>> = {
  address: {
    accountno: "Account Number",
    addresslon: "Property Address",
    label: "Address",
    edt: "Effective Date",
    esn: "Emergency Service Number",
    fsa: "Street Address",
    fsan: "Street Number",
    geo_error: "Geocoding Quality",
    geoid10: "2010 Census GEOID",
    gid: "Internal GIS ID",
  },
  driveway: {
    gid: "Internal GIS ID",
  },
  exempt: {
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    managingag: "Managing Agency",
  },
  jurisdictions: {
    date: "Effective Date",
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    identifier: "Jurisdiction Identifier",
    name: "Jurisdiction Name",
    squaremile: "Area (Square Miles)",
  },
  road: {
    community: "Community",
    date: "Effective Date",
    gid: "Internal GIS ID",
    label: "Road Label",
    labelstyle: "Road Classification",
    length_fee: "Length (Feet)",
    length_mil: "Length (Miles)",
    name: "Road Name",
    type: "Road Type",
  },
  sections: {
    assessorid: "Assessor Section ID",
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    gunncoadju: "Gunnison County Adjusted",
    label: "Section Label",
    last_edi_1: "Last Edit Date",
    section: "Section Number",
    survtyptxt: "Survey Type",
    townshipra: "Township / Range / Section",
    type: "Boundary Type",
  },
  subdivision: {
    bookannota: "Book Annotation",
    conveyanc1: "Subdivision Name",
    conveyanc2: "Document Type",
    conveyance: "Conveyance Number",
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    platdate: "Plat Date",
    reception: "Reception Number",
  },
  taxdistrict: {
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    taxdistric: "Tax District Number",
  },
  taxparcelassessor: {
    accountno: "Account Number",
    accounttyp: "Account Type",
    assessorac: "Assessed Acres",
    assessorre: "Property Record Link",
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    impsactual: "Improvement Actual Value",
    landactual: "Land Actual Value",
    legaldescr: "Legal Description",
  },
  towns: {
    abandoned: "Abandoned Status",
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    label: "Town Name",
    name: "Official Name",
    notes: "Incorporation Status",
    size: "Town Size Classification",
  },
  votingprecincts: {
    gid: "Internal GIS ID",
    gisacres: "GIS Acres",
    name: "Precinct Name",
    number: "Precinct Number",
  },
};
